name: Deploy Telegram Bot

on:
  push:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Ubuntu server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.SERVER_HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: |
            cd /opt/bots/bot-times-two
            ls -a

          debug: true
